### ISSUE TITLE
parallel bootstrap

### ISSUE THREAD

**Issue by viliusl** [wix/octopus#10]
This one is tricky, as you have to bootstrap in respect to dependency graph, but oh well.

Working code for inspiration is: https://github.com/laurynasl-wix/wnpm/commit/444cac4d7d8542fcae5a22c7bd94a940f1ffd845 + following commits for fixes.

Execution should just be properly tdd'ed of course:)

**Comment by viliusl** [comment]
@itaipelles - https://github.com/yarnpkg/yarn/issues/683 - ouch:/

In any case afaik there is only a question when it will be resolved and not if, so let's proceed. Also given engine is configurable we can see if in parallel scenario npm works better or do some other optimizations here.

**Comment by laurynasl-wix** [comment]
Btw, I think this only affects the cases where your yarn install puts stuff into the global cache, so if you're bootstrapping after a previous one, and yarn doesn't have to fetch identical dependencies from the registry, it doesn't blow up.

**Comment by viliusl** [comment]
it works with npm now
